name = "FrontCutTracking"
uuid = "0ec1a2bd-0df2-4d71-94d3-a499e1c962f8"
version = "0.1.0"
authors = ["PenguinxCutCell"]

[deps]
GeoInterface = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"
LibGEOS = "a90b1aa1-3769-5649-ba7e-abc5a9d163eb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
VofiJul = "e4b0aab4-58c8-425b-9d4c-54271c2045d0"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"

[compat]
GeoInterface = "1.4.1"
LibGEOS = "0.9.4"
LinearAlgebra = "1.11.0"
Test = "1.11.0"
VofiJul = "0.1.0"
WriteVTK = "1.21.2"
julia = "1"
